### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by ldkong1205** [xingyuuchen/tri-depth#1]
Hi @xingyuuchen, thank you for open-sourcing your work!

I would like to ask if it is possible for you to release the pretrained weights of TriDepth on KITTI for the purpose of reproduction. Thanks!

**Comment by xingyuuchen** [comment]
> Hi @xingyuuchen, thank you for open-sourcing your work!
> 
> I would like to ask if it is possible for you to release the pretrained weights of TriDepth on KITTI for the purpose of reproduction. Thanks!

Hi @ldkong1205,

The pretrained model (and the guidance for reproducing our results) will be released when the paper publish.

**Comment by ldkong1205** [comment]
Hi @xingyuuchen, thanks for your reply!

Is there an estimated time for the release? I am actually looking for just the evaluation part and pretrained models, is it possible that you can send them to me first? Thanks!

**Comment by xingyuuchen** [comment]
> Hi @xingyuuchen, thanks for your reply!
> 
> Is there an estimated time for the release? I am actually looking for just the evaluation part and pretrained models, is it possible that you can send them to me first? Thanks!

The arxiv pre-print version is being processed. The release may be in the next few days (It depends on arxiv).

**Comment by ldkong1205** [comment]
Hi @xingyuuchen, glad to know! Thank you for your help and looking forward to the models.

**Comment by xingyuuchen** [comment]
Hi @ldkong1205,

The pretrained model has already been released, please see the README.md file.

I'm gonna close this issue, thanks.

**Comment by ldkong1205** [comment]
> Hi, @ldkong1205,
> 
> The pretrained model has already been released, please see the README.md file.
> 
> I'm gonna close this issue, thanks.

Thank you for your help and congrats on your work!
