### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by XIAN-XIAN-X** [xingyuuchen/tri-depth#10]
Hello, it seems that the pre-trained model link cannot be downloaded

**Comment by xingyuuchen** [comment]
Hello @XIAN-XIAN-X ,

Thanks for your interests in my work!

I tries just now and it seems there's no problem dounloading from the [link](https://drive.google.com/file/d/1B75fdPv4lhFQ25Ba7l0gzscPg91mQUZC/view?usp=sharing).

<img width="430" alt="image" src="https://github.com/user-attachments/assets/a89b950b-3053-40ad-a9d6-e5da83f51b4d">

**Comment by XIAN-XIAN-X** [comment]
sorry,my network have some problem,could you provide the baidu diver link.Thansk a lot!

**Comment by XIAN-XIAN-X** [comment]
hello！When you train the model, do you load some pre-trained weights?

**Comment by XIAN-XIAN-X** [comment]
DO I need to set --mono_weights_folder or --load_weights_folder to get the pretrained weight for manydepths when i train the model.

**Comment by xingyuuchen** [comment]
> hello！When you train the model, do you load some pre-trained weights?

Load the image-net pre trained model. And this is the default config - you don't have to make any changes.

**Comment by XIAN-XIAN-X** [comment]
> > hello！When you train the model, do you load some pre-trained weights?
> 
> Load the image-net pre trained model. And this is the default config - you don't have to make any changes.

I got it.Thanks a lot!
