### ISSUE TITLE
tri trainer

### ISSUE THREAD

**Issue by Han-SHS** [xingyuuchen/tri-depth#4]
we find some error when we use your code to training our model，

‘seg_target = inputs[('seg', 0, 0)]‘show that there is no ’seg‘ in the inputs.

we notice that your code is based on FSRE and manydepth, so we copy the FSRE dataloader to tri-depth and debug the code, After making modifications to the data loader, we were able to successfully train our model using the provided code. We are curious to know if there are alternative methods for utilizing this code that we could explore

**Comment by xingyuuchen** [comment]
Hello @Han-SHS ,

Thanks for your interest!
Yes, you are right. [Issue 3](https://github.com/xingyuuchen/tri-depth/issues/3) also had the same problem.
Please do not forget to modify the file `kitti_dataset.py` and `mono_dataset.py` to load the segmentation images.
Here is the [line](https://github.com/xingyuuchen/tri-depth/blob/master/manydepth/datasets/kitti_dataset.py#L99) we load the segmentations.

However, this is just to load the segmentations as input, I do not get your point why you want other alternative methods?

Best,
Xingyu

**Comment by Han-SHS** [comment]
thanks for you reply

I saw the description of Issue 3, I'm just worried whether my above mentioned method of data loading with FSRE will affect the result

**Comment by xingyuuchen** [comment]
> thanks for you reply
> 
> I saw the description of Issue 3, I'm just worried whether my above mentioned method of data loading with FSRE will affect the result

I don't think this will affect the results, as the loading process of segmentations is not involved in the model training.

**Comment by xingyuuchen** [comment]
I'm closing this issue, feel free to reopen it again.
