### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by amundra15** [xingyuuchen/tri-depth#7]
Thanks for releasing your amazing work. I am wondering if the pre-trained model is for ManyDepth?

**Comment by xingyuuchen** [comment]
> Thanks for releasing your amazing work. I am wondering if the pre-trained model is for ManyDepth?

We use Manydepth as the baseline.
The network architechture is the same as Manydepth.

**Comment by amundra15** [comment]
Thanks for your quick response!

Since you also show results for MonoDepth2, can I request the pre-trained weights for that model as well?

**Comment by xingyuuchen** [comment]
> Thanks for your quick response!
> 
> Since you also show results for MonoDepth2, can I request the pre-trained weights for that model as well?

Sorry, I did not save that model. You can train it youself, it's quite simple~

**Comment by amundra15** [comment]
Alright, thanks for letting me know.
