### ISSUE TITLE
Question about computation of total losses.

### ISSUE THREAD

**Issue by Shaw-Way** [xingyuuchen/tri-depth#9]
Hi, author. Thanks for your remarkable work.
https://github.com/xingyuuchen/tri-depth/blob/4ae4085caff74f5e62eb0377266b4a817f40cbee/manydepth/trainer.py#L667-L681
I noticed that the total_loss isn't divided by num_scales like original Manydepth does. Would this have an influence on the results? And I don't understand why smooth_loss and reprojection_loss are divided  by 2**scale.
https://github.com/xingyuuchen/tri-depth/blob/4ae4085caff74f5e62eb0377266b4a817f40cbee/manydepth/trainer.py#L667
https://github.com/xingyuuchen/tri-depth/blob/4ae4085caff74f5e62eb0377266b4a817f40cbee/manydepth/trainer.py#L673

**Comment by Shaw-Way** [comment]
When applying the sgt_loss to other monocular depth estimation models, did you also make the same modifications, such as not dividing the total loss by num_scale and dividing reprojection_loss by 2**scale?

**Comment by xingyuuchen** [comment]
Hello @Shaw-Way ,
Thanks for your interest!

I remember the settings you mentioned were following [1], and there are no special considerations when I set these parameters.

[1]. Hyunyoung Jung, Eunhyeok Park, and Sungjoo Yoo. Fine- grained semantics-aware representation enhancement for self-supervised monocular depth estimation. In Proceedings of the IEEE/CVF International Conference on Computer Vi- sion, pages 12642–12652, 2021.

**Comment by Shaw-Way** [comment]
ok, thanks for your reply!
